// Package timeutil provides consistent time JSON serialization across the system.
// All cache serialization should use this package to ensure time.Time fields
// are marshaled/unmarshaled with nanosecond precision and timezone awareness.
package timeutil

import "time"

// JSONFormat is the canonical time format for JSON serialization.
// Using RFC3339Nano ensures nanosecond precision and timezone offset.
const JSONFormat = time.RFC3339Nano

// FormatJSON formats a time.Time for JSON serialization.
// Returns empty string for zero time.
func FormatJSON(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format(JSONFormat)
}

// ParseJSON parses a time string generated by FormatJSON.
// Returns zero time for empty input.
func ParseJSON(s string) (time.Time, error) {
	if s == "" {
		return time.Time{}, nil
	}
	t, err := time.Parse(JSONFormat, s)
	if err != nil {
		// Fallback: try RFC3339 (second precision) for backward compatibility
		t, err2 := time.Parse(time.RFC3339, s)
		if err2 != nil {
			return t, err // return original error
		}
		return t, nil
	}
	return t, nil
}

// MustParseJSON parses a time string and panics on error.
// Intended for use in tests and initialization code.
func MustParseJSON(s string) time.Time {
	t, err := ParseJSON(s)
	if err != nil {
		panic("timeutil: " + err.Error())
	}
	return t
}

// Now returns the current local time.
func Now() time.Time {
	return time.Now()
}
