-- ============================================================================
-- EasyMail bootstrap SQL
-- 1. Admin account (admin_users)
-- 2. Built-in anti-spam feature catalog (buildin_features)
-- ============================================================================
-- Usage: mysql -u root -p easymail < scripts/init.sql
-- ============================================================================

-- ============================================================================
-- 1. Admin account
-- ============================================================================
-- Default credentials: admin / admin888
INSERT INTO admin_users (id, username, password_hash, nickname, email, language, skin, active, is_deleted)
VALUES ('0c74d970-944a-4353-9099-25df63407e47', 'admin', '$2a$10$h6Jq29RJ4IXD04H/Bk/Y6ur6Ss3Nqe/rWCVxEViMRcCe0UUfB2JVC', 'admin', 'admin@example.com', 'zh', 'dark', 1, 0);

-- ============================================================================
-- 2. Built-in feature catalog (buildin_features)
-- ============================================================================
-- stage: 0=connect, 1=helo, 2=mail_from, 3=rcpt_to, 4=headers, 5=body
-- ============================================================================

INSERT INTO buildin_features
  (feature_key, label, value_type, description, unit, stage, created_at, updated_at)
VALUES

  -- STAGE 0 — CONNECT
  ('ip_ptr_ok',                    'IP PTR lookup OK',                    'bool',
   'At least one PTR (reverse DNS) record exists for the connecting IP',                   '',    0, NOW(), NOW()),
  ('ip_ptr_count',                 'IP PTR record count',                 'number',
   'Number of PTR records resolved for the connecting IP',                                'count',0, NOW(), NOW()),
  ('ip_ptr_has_dot',               'PTR name contains a dot',             'bool',
   'Whether the first PTR hostname contains at least one dot',                             '',    0, NOW(), NOW()),
  ('ip_fcrdns_ok',                 'IP FCrDNS OK',                        'bool',
   'Forward-confirmed rDNS: A/AAAA for the PTR name includes the original IP',             '',    0, NOW(), NOW()),
  ('ip_ptr_forward_match_count',   'FCrDNS match count',                  'number',
   'Number of PTR names (among first 3) that resolve back to the original IP',            'count',0, NOW(), NOW()),
  ('ip_connect_count_1d',          'IP connect count (local day)',        'number',
   'Connect events in the current local calendar day; Redis key includes YYYYMMDD, TTL 24h', 'count',0, NOW(), NOW()),
  ('ip_connect_count_5m',          'IP connect count (5 min)',            'number',
   'Connect events in a sliding 5-minute Redis window',                                  'count',0, NOW(), NOW()),
  ('ip_connect_rate_1d',           'IP connect rate (local day)',         'number',
   'ip_connect_count_1d / seconds elapsed since local midnight',                          'per_sec',0, NOW(), NOW()),
  ('ip_connect_rate_5m',           'IP connect rate (5 min)',             'number',
   'ip_connect_count_5m / 300 (sliding 5-minute window)',                                 'per_sec',0, NOW(), NOW()),
  ('ip_outcome_accept_1d',         'IP outcome accept (local day)',       'number',
   'Accepted-session count for this IP in the current local calendar day',                'count',0, NOW(), NOW()),
  ('ip_outcome_reject_1d',         'IP outcome reject (local day)',       'number',
   'Rejected-session count for this IP in the current local calendar day',                'count',0, NOW(), NOW()),
  ('ip_outcome_spam_1d',           'IP outcome spam (local day)',         'number',
   'Spam-classified session count for this IP in the current local calendar day',          'count',0, NOW(), NOW()),
  ('ip_outcome_quarantine_1d',     'IP outcome quarantine (local day)',   'number',
   'Quarantined-session count for this IP in the current local calendar day',              'count',0, NOW(), NOW()),
  ('ip_outcome_total_1d',          'IP outcome total (local day)',        'number',
   'Sum of all outcomes (accept+reject+spam+quarantine) for this IP today',                'count',0, NOW(), NOW()),
  ('ip_reject_rate_1d',            'IP reject rate (local day)',          'number',
   'reject / total outcomes for this IP in the current local calendar day',                'ratio',0, NOW(), NOW()),
  ('ip_reject_rate_5m',            'IP reject rate (5 min)',              'number',
   'reject / total outcomes for this IP in the sliding 5-minute window',                   'ratio',0, NOW(), NOW()),

  -- STAGE 1 — HELO
  ('helo_present',                 'HELO present',                        'bool',
   'Whether the client sent a non-empty HELO/EHLO hostname',                               '',    1, NOW(), NOW()),
  ('helo_rdns_match',              'HELO matches rDNS',                   'bool',
   'HELO hostname equals or suffixes any PTR name (among first 3 records)',                 '',    1, NOW(), NOW()),
  ('helo_rdns_name_count',         'rDNS names compared for HELO',        'number',
   'Number of PTR names used for HELO-to-rDNS comparison (up to 3)',                      'count',1, NOW(), NOW()),

  -- STAGE 2 — MAIL FROM
  ('sender_domain_has_mx',         'Sender domain has MX',                'bool',
   'MAIL FROM domain has at least one MX record in DNS',                                   '',    2, NOW(), NOW()),
  ('sender_domain_has_a',          'Sender domain has A/AAAA',            'bool',
   'MAIL FROM domain has at least one A or AAAA record in DNS',                             '',    2, NOW(), NOW()),
  ('sender_domain_mx_count',       'Sender domain MX count',              'number',
   'Number of MX records found for the MAIL FROM domain',                                  'count',2, NOW(), NOW()),
  ('sender_domain_mx_pref_min',    'Sender domain min MX preference',     'number',
   'Lowest (best) MX preference value among all MX records',                                '',    2, NOW(), NOW()),
  ('sender_domain_mx_is_null',     'Sender domain null MX (RFC 7505)',    'bool',
   'Whether any MX host is "." indicating the domain does not accept email (RFC 7505)',    '',    2, NOW(), NOW()),
  ('sender_domain_a_count',        'Sender domain A/AAAA count',          'number',
   'Number of A and AAAA records found for the MAIL FROM domain',                          'count',2, NOW(), NOW()),
  ('sender_mailfrom_count_1d',     'Sender MAIL FROM count (local day)',  'number',
   'MAIL FROM events for this sender in the current local calendar day; Redis YYYYMMDD, TTL 24h', 'count',2, NOW(), NOW()),
  ('sender_mailfrom_count_5m',     'Sender MAIL FROM count (5 min)',      'number',
   'MAIL FROM events for this sender in a sliding 5-minute Redis window',                  'count',2, NOW(), NOW()),
  ('sender_outcome_accept_1d',     'Sender outcome accept (local day)',   'number',
   'Accepted-session count for this sender in the current local calendar day',             'count',2, NOW(), NOW()),
  ('sender_outcome_reject_1d',     'Sender outcome reject (local day)',   'number',
   'Rejected-session count for this sender in the current local calendar day',             'count',2, NOW(), NOW()),
  ('sender_outcome_spam_1d',       'Sender outcome spam (local day)',     'number',
   'Spam-classified session count for this sender in the current local calendar day',      'count',2, NOW(), NOW()),
  ('sender_outcome_quarantine_1d', 'Sender outcome quarantine (local day)', 'number',
   'Quarantined-session count for this sender in the current local calendar day',          'count',2, NOW(), NOW()),
  ('sender_outcome_total_1d',      'Sender outcome total (local day)',    'number',
   'Sum of all outcomes for this sender today',                                            'count',2, NOW(), NOW()),
  ('sender_reject_rate_1d',        'Sender reject rate (local day)',      'number',
   'reject / total outcomes for this sender in the current local calendar day',            'ratio',2, NOW(), NOW()),
  ('spf_result',                   'SPF result code',                     'number',
   'Numeric SPF result: 0=None, 1=Neutral, 2=Pass, 3=SoftFail, 4=Fail, 5=TempError, 6=PermError', '', 2, NOW(), NOW()),
  ('spf_pass',                     'SPF pass',                            'bool',
   'SPF evaluation result is Pass',                                                         '',    2, NOW(), NOW()),
  ('spf_fail',                     'SPF fail or softfail',                'bool',
   'SPF evaluation result is Fail or SoftFail',                                             '',    2, NOW(), NOW()),
  ('spf_softfail',                 'SPF softfail',                        'bool',
   'SPF evaluation result is SoftFail',                                                     '',    2, NOW(), NOW()),
  ('spf_neutral',                  'SPF neutral',                         'bool',
   'SPF evaluation result is Neutral',                                                      '',    2, NOW(), NOW()),
  ('spf_none',                     'SPF none',                            'bool',
   'No SPF record found for the sender domain (result=None)',                               '',    2, NOW(), NOW()),
  ('spf_error',                    'SPF error (temperror/permerror)',     'bool',
   'SPF evaluation resulted in TempError or PermError',                                     '',    2, NOW(), NOW()),
  ('spf_skipped',                  'SPF skipped',                         'bool',
   'SPF check was skipped (no connection IP, no sender, no domain, or no resolver)',        '',    2, NOW(), NOW()),

  -- STAGE 3 — RCPT TO
  ('rcpt_count',                   'Envelope recipient count',            'number',
   'Number of RCPT TO commands for this message',                                          'count',3, NOW(), NOW()),
  ('sender_has_mailfrom',          'MAIL FROM present',                   'bool',
   'Whether MAIL FROM address is non-empty',                                                '',    3, NOW(), NOW()),
  ('sender_rcpt_count',            'Sender-scoped RCPT count',            'number',
   'Same as rcpt_count; alias for sender-namespace rules',                                 'count',3, NOW(), NOW()),
  ('rcpt_domain_present',          'Recipient domain present',            'bool',
   'Whether the RCPT TO address includes a domain part',                                    '',    3, NOW(), NOW()),
  ('sender_rcpt_domain_count_1d',  'Sender->domain count (local day)',    'number',
   'Count for the (sender, rcpt_domain) pair in the current local calendar day',           'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_count_5m',  'Sender->domain count (5 min)',        'number',
   'Count for the (sender, rcpt_domain) pair in a sliding 5-minute Redis window',          'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_accept_1d', 'Sender->domain accept (local day)',   'number',
   'Accepted count for (sender, rcpt_domain) in the current local calendar day',           'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_reject_1d', 'Sender->domain reject (local day)',   'number',
   'Rejected count for (sender, rcpt_domain) in the current local calendar day',           'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_spam_1d',   'Sender->domain spam (local day)',     'number',
   'Spam count for (sender, rcpt_domain) in the current local calendar day',               'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_quarantine_1d', 'Sender->domain quarantine (local day)', 'number',
   'Quarantine count for (sender, rcpt_domain) in the current local calendar day',         'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_total_1d',  'Sender->domain total (local day)',    'number',
   'Sum of all outcomes for (sender, rcpt_domain) today',                                  'count',3, NOW(), NOW()),
  ('sender_rcpt_domain_reject_rate_1d', 'Sender->domain reject rate (local day)', 'number',
   'reject / total outcomes for (sender, rcpt_domain) in the current local calendar day',  'ratio',3, NOW(), NOW()),
  ('rcpt_domain_is_local',         'Recipient domain is local',           'bool',
   'Whether the recipient domain exists and is valid in the local domains table',            '',    3, NOW(), NOW()),
  ('rcpt_mailbox_exists',          'Recipient mailbox exists',            'bool',
   'Whether a valid active account exists for (recipient_username, recipient_domain)',       '',    3, NOW(), NOW()),
  ('rcpt_contact_sender_hit',      'Sender in recipient contacts',        'bool',
   'Whether the sender email appears in the recipient\'s address book (contacts)',          '',    3, NOW(), NOW()),

  -- STAGE 4 — HEADERS
  ('header_fields',                'Header field count',                  'number',
   'Number of MIME header fields present at end-of-headers stage',                         'count',4, NOW(), NOW()),

  -- STAGE 5 — BODY
  ('body_bytes',                   'Raw message body size',               'number',
   'Total raw byte length of the message body (RFC822 body)',                               'B',   5, NOW(), NOW()),
  ('body_bytes_partial',           'Session body bytes (incomplete)',      'number',
   'Cumulative milter BodyChunk length for early-stage partial inspection',                 'B',   5, NOW(), NOW()),
  ('subject_len',                  'Subject length',                      'number',
   'Decoded Subject header value length in Unicode rune count',                            'chars',5, NOW(), NOW()),
  ('has_list_unsubscribe',         'Has List-Unsubscribe header',         'bool',
   'Whether the List-Unsubscribe header is present in the message',                         '',    5, NOW(), NOW()),
  ('mime_part_count',              'MIME part count',                     'number',
   'Number of MIME parts (nodes) identified by enmime parser',                             'count',5, NOW(), NOW()),
  ('attachment_count',             'Attachment count',                    'number',
   'Number of attachments (files) extracted from the MIME structure',                      'count',5, NOW(), NOW()),
  ('body_url_count',               'Body URL count',                      'number',
   'Number of http/https URLs extracted from the message body (HTML + text)',              'count',5, NOW(), NOW()),
  ('body_url_has_http',            'Body includes http:// URL',           'bool',
   'Whether at least one URL in the body uses plain http:// scheme',                        '',    5, NOW(), NOW()),
  ('body_url_has_https',           'Body includes https:// URL',          'bool',
   'Whether at least one URL in the body uses https:// scheme',                             '',    5, NOW(), NOW()),
  ('body_url_short_count',         'Short/redirect URL count',            'number',
   'Number of URLs matching structural short-link patterns',                               'count',5, NOW(), NOW()),
  ('body_url_has_short',           'Body has short redirect URL',         'bool',
   'Whether any body URL matches the structural short-link pattern',                        '',    5, NOW(), NOW()),
  ('attachment_risky_ext_count',   'Risky attachment extension count',    'number',
   'Number of attachments with high-risk extensions (exe, dll, scr, bat, cmd, ps1, vbs, js, etc.)', 'count',5, NOW(), NOW()),
  ('attachment_risky_ext_ratio',   'Risky attachment ratio',              'number',
   'Risky attachments divided by total attachments (0.0-1.0)',                              'ratio',5, NOW(), NOW()),
  ('attachment_name_double_ext_cnt', 'Double-extension attachment count', 'number',
   'Number of attachments whose filename contains two or more dots',                        'count',5, NOW(), NOW()),
  ('antivirus_hit',                'Antivirus malware detected',          'number',
   'ClamAV or other antivirus engine flagged the message as malicious; -1 indicates failure', '', 5, NOW(), NOW()),
  ('dmarc_domain',                 'DMARC domain (placeholder)',          'number',
   'Placeholder key; always 0 in current implementation',                                   '',    5, NOW(), NOW()),
  ('dmarc_has_policy',             'DMARC policy record found',           'bool',
   'Whether a parseable DMARC DNS policy record exists for the From domain',                '',    5, NOW(), NOW()),
  ('dmarc_policy_none',            'DMARC policy p=none',                 'bool',
   'Published DMARC policy is p=none (no enforcement)',                                     '',    5, NOW(), NOW()),
  ('dmarc_policy_quarantine',      'DMARC policy p=quarantine',           'bool',
   'Published DMARC policy is p=quarantine (send to spam/quarantine)',                      '',    5, NOW(), NOW()),
  ('dmarc_policy_reject',          'DMARC policy p=reject',               'bool',
   'Published DMARC policy is p=reject (reject non-aligned mail)',                          '',    5, NOW(), NOW()),
  ('dmarc_policy_code',            'DMARC policy numeric code',           'number',
   'Numeric DMARC policy: 0=none, 1=quarantine, 2=reject',                                  '',    5, NOW(), NOW()),
  ('dmarc_spf_aligned',            'DMARC SPF aligned',                   'bool',
   'SPF-authenticated domain aligns with the From domain (relaxed/org-domain mode)',         '',    5, NOW(), NOW()),
  ('dmarc_dkim_aligned',           'DMARC DKIM aligned',                  'bool',
   'At least one DKIM signing domain aligns with the From domain (relaxed mode)',            '',    5, NOW(), NOW()),
  ('dmarc_spf_domain_match',       'DMARC SPF domain match',              'bool',
   'Same as dmarc_spf_aligned - duplicate key for rule flexibility',                        '',    5, NOW(), NOW()),
  ('dmarc_dkim_domain_match',      'DMARC DKIM domain match',             'bool',
   'Same as dmarc_dkim_aligned - duplicate key for rule flexibility',                       '',    5, NOW(), NOW()),
  ('dmarc_result',                 'DMARC result',                        'number',
   'DMARC evaluation outcome: 0=None, 1=Pass, 2=Fail',                                     '',    5, NOW(), NOW()),
  ('dmarc_pass',                   'DMARC pass',                          'bool',
   'DMARC check passed (SPF or DKIM aligned with From domain)',                             '',    5, NOW(), NOW()),
  ('dmarc_fail',                   'DMARC fail',                          'bool',
   'DMARC check failed (neither SPF nor DKIM aligned, policy is quarantine or reject)',     '',    5, NOW(), NOW()),
  ('dkim_result',                  'DKIM overall result',                 'number',
   'Overall DKIM verification result: 0=None, 1=Pass, 2=Fail, 3=TempError, 4=PermError',   '',    5, NOW(), NOW()),
  ('dkim_pass',                    'DKIM pass',                           'bool',
   'At least one DKIM-Signature passed cryptographic verification',                         '',    5, NOW(), NOW()),
  ('dkim_fail',                    'DKIM fail',                           'bool',
   'All DKIM-Signatures failed verification (no passing signature)',                        '',    5, NOW(), NOW()),
  ('dkim_sig_count',               'DKIM signature count',                'number',
   'Total number of DKIM-Signature header fields found in the message',                    'count',5, NOW(), NOW()),
  ('dkim_pass_count',              'DKIM passing signature count',        'number',
   'Number of DKIM-Signatures that passed cryptographic verification',                     'count',5, NOW(), NOW()),
  ('dkim_fail_count',              'DKIM failing signature count',        'number',
   'Number of DKIM-Signatures that failed verification',                                    'count',5, NOW(), NOW()),
  ('dkim_verified_count',          'DKIM verified signature count',       'number',
   'Same as dkim_pass_count - alias for rule flexibility',                                  'count',5, NOW(), NOW()),
  ('dkim_skipped',                 'DKIM skipped',                        'bool',
   'DKIM verification was skipped (no headers, no body, or nil context)',                   '',    5, NOW(), NOW())

ON DUPLICATE KEY UPDATE
  label       = VALUES(label),
  value_type  = VALUES(value_type),
  description = VALUES(description),
  unit        = VALUES(unit),
  stage       = VALUES(stage),
  updated_at  = NOW();