package migrate

import (
	"time"

	"easymail/internal/infrastructure/persistence/mysql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// FilterBootstrap seeds built-in anti-spam feature definitions into the
// buildin_features table. Safe to run repeatedly — uses OnConflict
// with column updates so new keys are inserted and existing labels/text
// are refreshed.
func FilterBootstrap(db *gorm.DB) error {
	now := time.Now()
	features := []mysql.BuiltinFeaturePO{
		// ---- STAGE 0 — CONNECT ----
		{FeatureKey: "ip_ptr_ok", Label: "IP PTR lookup OK", ValueType: "bool", Stage: 0,
			Description: "At least one PTR (reverse DNS) record exists for the connecting IP", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_ptr_count", Label: "IP PTR record count", ValueType: "number", Stage: 0,
			Description: "Number of PTR records resolved for the connecting IP", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_ptr_has_dot", Label: "PTR name contains a dot", ValueType: "bool", Stage: 0,
			Description: "Whether the first PTR hostname contains at least one dot", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_fcrdns_ok", Label: "IP FCrDNS OK", ValueType: "bool", Stage: 0,
			Description: "Forward-confirmed rDNS: A/AAAA for the PTR name includes the original IP", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_ptr_forward_match_count", Label: "FCrDNS match count", ValueType: "number", Stage: 0,
			Description: "Number of PTR names (among first 3) that resolve back to the original IP", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_connect_count_1d", Label: "IP connect count (local day)", ValueType: "number", Stage: 0,
			Description: "Connect events in the current local calendar day; Redis key includes YYYYMMDD, TTL 24h", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_connect_count_5m", Label: "IP connect count (5 min)", ValueType: "number", Stage: 0,
			Description: "Connect events in a sliding 5-minute Redis window", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_connect_rate_1d", Label: "IP connect rate (local day)", ValueType: "number", Stage: 0,
			Description: "ip_connect_count_1d / seconds elapsed since local midnight", Unit: "per_sec", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_connect_rate_5m", Label: "IP connect rate (5 min)", ValueType: "number", Stage: 0,
			Description: "ip_connect_count_5m / 300 (sliding 5-minute window)", Unit: "per_sec", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_outcome_accept_1d", Label: "IP outcome accept (local day)", ValueType: "number", Stage: 0,
			Description: "Accepted-session count for this IP in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_outcome_reject_1d", Label: "IP outcome reject (local day)", ValueType: "number", Stage: 0,
			Description: "Rejected-session count for this IP in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_outcome_spam_1d", Label: "IP outcome spam (local day)", ValueType: "number", Stage: 0,
			Description: "Spam-classified session count for this IP in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_outcome_quarantine_1d", Label: "IP outcome quarantine (local day)", ValueType: "number", Stage: 0,
			Description: "Quarantined-session count for this IP in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_outcome_total_1d", Label: "IP outcome total (local day)", ValueType: "number", Stage: 0,
			Description: "Sum of all outcomes (accept+reject+spam+quarantine) for this IP today", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_reject_rate_1d", Label: "IP reject rate (local day)", ValueType: "number", Stage: 0,
			Description: "reject / total outcomes for this IP in the current local calendar day", Unit: "ratio", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "ip_reject_rate_5m", Label: "IP reject rate (5 min)", ValueType: "number", Stage: 0,
			Description: "reject / total outcomes for this IP in the sliding 5-minute window", Unit: "ratio", CreatedAt: now, UpdatedAt: now},

		// ---- STAGE 1 — HELO ----
		{FeatureKey: "helo_present", Label: "HELO present", ValueType: "bool", Stage: 1,
			Description: "Whether the client sent a non-empty HELO/EHLO hostname", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "helo_rdns_match", Label: "HELO matches rDNS", ValueType: "bool", Stage: 1,
			Description: "HELO hostname equals or suffixes any PTR name (among first 3 records)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "helo_rdns_name_count", Label: "rDNS names compared for HELO", ValueType: "number", Stage: 1,
			Description: "Number of PTR names used for HELO-to-rDNS comparison (up to 3)", Unit: "count", CreatedAt: now, UpdatedAt: now},

		// ---- STAGE 2 — MAIL FROM ----
		{FeatureKey: "sender_domain_has_mx", Label: "Sender domain has MX", ValueType: "bool", Stage: 2,
			Description: "MAIL FROM domain has at least one MX record in DNS", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_domain_has_a", Label: "Sender domain has A/AAAA", ValueType: "bool", Stage: 2,
			Description: "MAIL FROM domain has at least one A or AAAA record in DNS", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_domain_mx_count", Label: "Sender domain MX count", ValueType: "number", Stage: 2,
			Description: "Number of MX records found for the MAIL FROM domain", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_domain_mx_pref_min", Label: "Sender domain min MX preference", ValueType: "number", Stage: 2,
			Description: "Lowest (best) MX preference value among all MX records", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_domain_mx_is_null", Label: "Sender domain null MX (RFC 7505)", ValueType: "bool", Stage: 2,
			Description: "Whether any MX host is \".\" indicating the domain does not accept email (RFC 7505)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_domain_a_count", Label: "Sender domain A/AAAA count", ValueType: "number", Stage: 2,
			Description: "Number of A and AAAA records found for the MAIL FROM domain", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_mailfrom_count_1d", Label: "Sender MAIL FROM count (local day)", ValueType: "number", Stage: 2,
			Description: "MAIL FROM events for this sender in the current local calendar day; Redis YYYYMMDD, TTL 24h", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_mailfrom_count_5m", Label: "Sender MAIL FROM count (5 min)", ValueType: "number", Stage: 2,
			Description: "MAIL FROM events for this sender in a sliding 5-minute Redis window", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_outcome_accept_1d", Label: "Sender outcome accept (local day)", ValueType: "number", Stage: 2,
			Description: "Accepted-session count for this sender in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_outcome_reject_1d", Label: "Sender outcome reject (local day)", ValueType: "number", Stage: 2,
			Description: "Rejected-session count for this sender in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_outcome_spam_1d", Label: "Sender outcome spam (local day)", ValueType: "number", Stage: 2,
			Description: "Spam-classified session count for this sender in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_outcome_quarantine_1d", Label: "Sender outcome quarantine (local day)", ValueType: "number", Stage: 2,
			Description: "Quarantined-session count for this sender in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_outcome_total_1d", Label: "Sender outcome total (local day)", ValueType: "number", Stage: 2,
			Description: "Sum of all outcomes for this sender today", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_reject_rate_1d", Label: "Sender reject rate (local day)", ValueType: "number", Stage: 2,
			Description: "reject / total outcomes for this sender in the current local calendar day", Unit: "ratio", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_result", Label: "SPF result code", ValueType: "number", Stage: 2,
			Description: "Numeric SPF result: 0=None, 1=Neutral, 2=Pass, 3=SoftFail, 4=Fail, 5=TempError, 6=PermError", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_pass", Label: "SPF pass", ValueType: "bool", Stage: 2,
			Description: "SPF evaluation result is Pass", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_fail", Label: "SPF fail or softfail", ValueType: "bool", Stage: 2,
			Description: "SPF evaluation result is Fail or SoftFail", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_softfail", Label: "SPF softfail", ValueType: "bool", Stage: 2,
			Description: "SPF evaluation result is SoftFail", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_neutral", Label: "SPF neutral", ValueType: "bool", Stage: 2,
			Description: "SPF evaluation result is Neutral", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_none", Label: "SPF none", ValueType: "bool", Stage: 2,
			Description: "No SPF record found for the sender domain (result=None)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_error", Label: "SPF error (temperror/permerror)", ValueType: "bool", Stage: 2,
			Description: "SPF evaluation resulted in TempError or PermError", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "spf_skipped", Label: "SPF skipped", ValueType: "bool", Stage: 2,
			Description: "SPF check was skipped (no connection IP, no sender, no domain, or no resolver)", Unit: "", CreatedAt: now, UpdatedAt: now},

		// ---- STAGE 3 — RCPT TO ----
		{FeatureKey: "rcpt_count", Label: "Envelope recipient count", ValueType: "number", Stage: 3,
			Description: "Number of RCPT TO commands for this message", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_has_mailfrom", Label: "MAIL FROM present", ValueType: "bool", Stage: 3,
			Description: "Whether MAIL FROM address is non-empty", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_count", Label: "Sender-scoped RCPT count", ValueType: "number", Stage: 3,
			Description: "Same as rcpt_count; alias for sender-namespace rules", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "rcpt_domain_present", Label: "Recipient domain present", ValueType: "bool", Stage: 3,
			Description: "Whether the RCPT TO address includes a domain part", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_count_1d", Label: "Sender->domain count (local day)", ValueType: "number", Stage: 3,
			Description: "Count for the (sender, rcpt_domain) pair in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_count_5m", Label: "Sender->domain count (5 min)", ValueType: "number", Stage: 3,
			Description: "Count for the (sender, rcpt_domain) pair in a sliding 5-minute Redis window", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_accept_1d", Label: "Sender->domain accept (local day)", ValueType: "number", Stage: 3,
			Description: "Accepted count for (sender, rcpt_domain) in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_reject_1d", Label: "Sender->domain reject (local day)", ValueType: "number", Stage: 3,
			Description: "Rejected count for (sender, rcpt_domain) in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_spam_1d", Label: "Sender->domain spam (local day)", ValueType: "number", Stage: 3,
			Description: "Spam count for (sender, rcpt_domain) in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_quarantine_1d", Label: "Sender->domain quarantine (local day)", ValueType: "number", Stage: 3,
			Description: "Quarantine count for (sender, rcpt_domain) in the current local calendar day", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_total_1d", Label: "Sender->domain total (local day)", ValueType: "number", Stage: 3,
			Description: "Sum of all outcomes for (sender, rcpt_domain) today", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "sender_rcpt_domain_reject_rate_1d", Label: "Sender->domain reject rate (local day)", ValueType: "number", Stage: 3,
			Description: "reject / total outcomes for (sender, rcpt_domain) in the current local calendar day", Unit: "ratio", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "rcpt_domain_is_local", Label: "Recipient domain is local", ValueType: "bool", Stage: 3,
			Description: "Whether the recipient domain exists and is valid in the local domains table", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "rcpt_mailbox_exists", Label: "Recipient mailbox exists", ValueType: "bool", Stage: 3,
			Description: "Whether a valid active account exists for (recipient_username, recipient_domain)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "rcpt_contact_sender_hit", Label: "Sender in recipient contacts", ValueType: "bool", Stage: 3,
			Description: "Whether the sender email appears in the recipient's address book (contacts)", Unit: "", CreatedAt: now, UpdatedAt: now},

		// ---- STAGE 4 — HEADERS ----
		{FeatureKey: "header_fields", Label: "Header field count", ValueType: "number", Stage: 4,
			Description: "Number of MIME header fields present at end-of-headers stage", Unit: "count", CreatedAt: now, UpdatedAt: now},

		// ---- STAGE 5 — BODY ----
		{FeatureKey: "body_bytes", Label: "Raw message body size", ValueType: "number", Stage: 5,
			Description: "Total raw byte length of the message body (RFC822 body)", Unit: "B", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "body_bytes_partial", Label: "Session body bytes (incomplete)", ValueType: "number", Stage: 5,
			Description: "Cumulative milter BodyChunk length for early-stage partial inspection", Unit: "B", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "subject_len", Label: "Subject length", ValueType: "number", Stage: 5,
			Description: "Decoded Subject header value length in Unicode rune count", Unit: "chars", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "has_list_unsubscribe", Label: "Has List-Unsubscribe header", ValueType: "bool", Stage: 5,
			Description: "Whether the List-Unsubscribe header is present in the message", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "mime_part_count", Label: "MIME part count", ValueType: "number", Stage: 5,
			Description: "Number of MIME parts (nodes) identified by enmime parser", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "attachment_count", Label: "Attachment count", ValueType: "number", Stage: 5,
			Description: "Number of attachments (files) extracted from the MIME structure", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "body_url_count", Label: "Body URL count", ValueType: "number", Stage: 5,
			Description: "Number of http/https URLs extracted from the message body (HTML + text)", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "body_url_has_http", Label: "Body includes http:// URL", ValueType: "bool", Stage: 5,
			Description: "Whether at least one URL in the body uses plain http:// scheme", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "body_url_has_https", Label: "Body includes https:// URL", ValueType: "bool", Stage: 5,
			Description: "Whether at least one URL in the body uses https:// scheme", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "body_url_short_count", Label: "Short/redirect URL count", ValueType: "number", Stage: 5,
			Description: "Number of URLs matching structural short-link patterns", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "body_url_has_short", Label: "Body has short redirect URL", ValueType: "bool", Stage: 5,
			Description: "Whether any body URL matches the structural short-link pattern", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "attachment_risky_ext_count", Label: "Risky attachment extension count", ValueType: "number", Stage: 5,
			Description: "Number of attachments with high-risk extensions (exe, dll, scr, bat, cmd, ps1, vbs, js, etc.)", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "attachment_risky_ext_ratio", Label: "Risky attachment ratio", ValueType: "number", Stage: 5,
			Description: "Risky attachments divided by total attachments (0.0-1.0)", Unit: "ratio", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "attachment_name_double_ext_cnt", Label: "Double-extension attachment count", ValueType: "number", Stage: 5,
			Description: "Number of attachments whose filename contains two or more dots", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "antivirus_hit", Label: "Antivirus malware detected", ValueType: "number", Stage: 5,
			Description: "ClamAV or other antivirus engine flagged the message as malicious; -1 indicates failure", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_domain", Label: "DMARC domain (placeholder)", ValueType: "number", Stage: 5,
			Description: "Placeholder key; always 0 in current implementation", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_has_policy", Label: "DMARC policy record found", ValueType: "bool", Stage: 5,
			Description: "Whether a parseable DMARC DNS policy record exists for the From domain", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_policy_none", Label: "DMARC policy p=none", ValueType: "bool", Stage: 5,
			Description: "Published DMARC policy is p=none (no enforcement)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_policy_quarantine", Label: "DMARC policy p=quarantine", ValueType: "bool", Stage: 5,
			Description: "Published DMARC policy is p=quarantine (send to spam/quarantine)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_policy_reject", Label: "DMARC policy p=reject", ValueType: "bool", Stage: 5,
			Description: "Published DMARC policy is p=reject (reject non-aligned mail)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_policy_code", Label: "DMARC policy numeric code", ValueType: "number", Stage: 5,
			Description: "Numeric DMARC policy: 0=none, 1=quarantine, 2=reject", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_spf_aligned", Label: "DMARC SPF aligned", ValueType: "bool", Stage: 5,
			Description: "SPF-authenticated domain aligns with the From domain (relaxed/org-domain mode)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_dkim_aligned", Label: "DMARC DKIM aligned", ValueType: "bool", Stage: 5,
			Description: "At least one DKIM signing domain aligns with the From domain (relaxed mode)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_spf_domain_match", Label: "DMARC SPF domain match", ValueType: "bool", Stage: 5,
			Description: "Same as dmarc_spf_aligned - duplicate key for rule flexibility", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_dkim_domain_match", Label: "DMARC DKIM domain match", ValueType: "bool", Stage: 5,
			Description: "Same as dmarc_dkim_aligned - duplicate key for rule flexibility", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_result", Label: "DMARC result", ValueType: "number", Stage: 5,
			Description: "DMARC evaluation outcome: 0=None, 1=Pass, 2=Fail", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_pass", Label: "DMARC pass", ValueType: "bool", Stage: 5,
			Description: "DMARC check passed (SPF or DKIM aligned with From domain)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dmarc_fail", Label: "DMARC fail", ValueType: "bool", Stage: 5,
			Description: "DMARC check failed (neither SPF nor DKIM aligned, policy is quarantine or reject)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_result", Label: "DKIM overall result", ValueType: "number", Stage: 5,
			Description: "Overall DKIM verification result: 0=None, 1=Pass, 2=Fail, 3=TempError, 4=PermError", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_pass", Label: "DKIM pass", ValueType: "bool", Stage: 5,
			Description: "At least one DKIM-Signature passed cryptographic verification", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_fail", Label: "DKIM fail", ValueType: "bool", Stage: 5,
			Description: "All DKIM-Signatures failed verification (no passing signature)", Unit: "", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_sig_count", Label: "DKIM signature count", ValueType: "number", Stage: 5,
			Description: "Total number of DKIM-Signature header fields found in the message", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_pass_count", Label: "DKIM passing signature count", ValueType: "number", Stage: 5,
			Description: "Number of DKIM-Signatures that passed cryptographic verification", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_fail_count", Label: "DKIM failing signature count", ValueType: "number", Stage: 5,
			Description: "Number of DKIM-Signatures that failed verification", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_verified_count", Label: "DKIM verified signature count", ValueType: "number", Stage: 5,
			Description: "Same as dkim_pass_count - alias for rule flexibility", Unit: "count", CreatedAt: now, UpdatedAt: now},
		{FeatureKey: "dkim_skipped", Label: "DKIM skipped", ValueType: "bool", Stage: 5,
			Description: "DKIM verification was skipped (no headers, no body, or nil context)", Unit: "", CreatedAt: now, UpdatedAt: now},
	}
	return db.Clauses(clause.OnConflict{
		Columns: []clause.Column{{Name: "feature_key"}},
		DoUpdates: clause.AssignmentColumns([]string{
			"label", "value_type", "description", "unit", "stage", "updated_at",
		}),
	}).Create(&features).Error
}