// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: filtermodel/v1/filtermodel.proto

package filtermodelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// BCP-47 or ISO-639 codes the client collected from the message (e.g. "en", "zh").
	LanguageCodes []string `protobuf:"bytes,2,rep,name=language_codes,json=languageCodes,proto3" json:"language_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_filtermodel_v1_filtermodel_proto_rawDescGZIP(), []int{0}
}

func (x *InferRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InferRequest) GetLanguageCodes() []string {
	if x != nil {
		return x.LanguageCodes
	}
	return nil
}

type LabelProbability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Probability   float64                `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelProbability) Reset() {
	*x = LabelProbability{}
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelProbability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelProbability) ProtoMessage() {}

func (x *LabelProbability) ProtoReflect() protoreflect.Message {
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelProbability.ProtoReflect.Descriptor instead.
func (*LabelProbability) Descriptor() ([]byte, []int) {
	return file_filtermodel_v1_filtermodel_proto_rawDescGZIP(), []int{1}
}

func (x *LabelProbability) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelProbability) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

type ModelPrediction struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ModelId     string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelName   string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Label       string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Probability float64                `protobuf:"fixed64,4,opt,name=probability,proto3" json:"probability,omitempty"`
	// Non-empty if this model failed; others may still succeed.
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Full class distribution on success (model-defined label order).
	LabelProbabilities []*LabelProbability `protobuf:"bytes,6,rep,name=label_probabilities,json=labelProbabilities,proto3" json:"label_probabilities,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelPrediction) Reset() {
	*x = ModelPrediction{}
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPrediction) ProtoMessage() {}

func (x *ModelPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPrediction.ProtoReflect.Descriptor instead.
func (*ModelPrediction) Descriptor() ([]byte, []int) {
	return file_filtermodel_v1_filtermodel_proto_rawDescGZIP(), []int{2}
}

func (x *ModelPrediction) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelPrediction) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelPrediction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ModelPrediction) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *ModelPrediction) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ModelPrediction) GetLabelProbabilities() []*LabelProbability {
	if x != nil {
		return x.LabelProbabilities
	}
	return nil
}

type InferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []*ModelPrediction     `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filtermodel_v1_filtermodel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_filtermodel_v1_filtermodel_proto_rawDescGZIP(), []int{3}
}

func (x *InferResponse) GetPredictions() []*ModelPrediction {
	if x != nil {
		return x.Predictions
	}
	return nil
}

var File_filtermodel_v1_filtermodel_proto protoreflect.FileDescriptor

const file_filtermodel_v1_filtermodel_proto_rawDesc = "" +
	"\n" +
	" filtermodel/v1/filtermodel.proto\x12\x17easymail.filtermodel.v1\"I\n" +
	"\fInferRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12%\n" +
	"\x0elanguage_codes\x18\x02 \x03(\tR\rlanguageCodes\"J\n" +
	"\x10LabelProbability\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\"\xf5\x01\n" +
	"\x0fModelPrediction\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12 \n" +
	"\vprobability\x18\x04 \x01(\x01R\vprobability\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12Z\n" +
	"\x13label_probabilities\x18\x06 \x03(\v2).easymail.filtermodel.v1.LabelProbabilityR\x12labelProbabilities\"[\n" +
	"\rInferResponse\x12J\n" +
	"\vpredictions\x18\x01 \x03(\v2(.easymail.filtermodel.v1.ModelPredictionR\vpredictions2l\n" +
	"\x12FilterModelService\x12V\n" +
	"\x05Infer\x12%.easymail.filtermodel.v1.InferRequest\x1a&.easymail.filtermodel.v1.InferResponseB4Z2easymail/internal/api/filtermodel/v1;filtermodelv1b\x06proto3"

var (
	file_filtermodel_v1_filtermodel_proto_rawDescOnce sync.Once
	file_filtermodel_v1_filtermodel_proto_rawDescData []byte
)

func file_filtermodel_v1_filtermodel_proto_rawDescGZIP() []byte {
	file_filtermodel_v1_filtermodel_proto_rawDescOnce.Do(func() {
		file_filtermodel_v1_filtermodel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filtermodel_v1_filtermodel_proto_rawDesc), len(file_filtermodel_v1_filtermodel_proto_rawDesc)))
	})
	return file_filtermodel_v1_filtermodel_proto_rawDescData
}

var file_filtermodel_v1_filtermodel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_filtermodel_v1_filtermodel_proto_goTypes = []any{
	(*InferRequest)(nil),     // 0: easymail.filtermodel.v1.InferRequest
	(*LabelProbability)(nil), // 1: easymail.filtermodel.v1.LabelProbability
	(*ModelPrediction)(nil),  // 2: easymail.filtermodel.v1.ModelPrediction
	(*InferResponse)(nil),    // 3: easymail.filtermodel.v1.InferResponse
}
var file_filtermodel_v1_filtermodel_proto_depIdxs = []int32{
	1, // 0: easymail.filtermodel.v1.ModelPrediction.label_probabilities:type_name -> easymail.filtermodel.v1.LabelProbability
	2, // 1: easymail.filtermodel.v1.InferResponse.predictions:type_name -> easymail.filtermodel.v1.ModelPrediction
	0, // 2: easymail.filtermodel.v1.FilterModelService.Infer:input_type -> easymail.filtermodel.v1.InferRequest
	3, // 3: easymail.filtermodel.v1.FilterModelService.Infer:output_type -> easymail.filtermodel.v1.InferResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_filtermodel_v1_filtermodel_proto_init() }
func file_filtermodel_v1_filtermodel_proto_init() {
	if File_filtermodel_v1_filtermodel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filtermodel_v1_filtermodel_proto_rawDesc), len(file_filtermodel_v1_filtermodel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filtermodel_v1_filtermodel_proto_goTypes,
		DependencyIndexes: file_filtermodel_v1_filtermodel_proto_depIdxs,
		MessageInfos:      file_filtermodel_v1_filtermodel_proto_msgTypes,
	}.Build()
	File_filtermodel_v1_filtermodel_proto = out.File
	file_filtermodel_v1_filtermodel_proto_goTypes = nil
	file_filtermodel_v1_filtermodel_proto_depIdxs = nil
}
