// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: filtermodel/v1/filtermodel.proto

package filtermodelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilterModelService_Infer_FullMethodName = "/easymail.filtermodel.v1.FilterModelService/Infer"
)

// FilterModelServiceClient is the classify-model Infer API client.
type FilterModelServiceClient interface {
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error)
}

type filterModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterModelServiceClient(cc grpc.ClientConnInterface) FilterModelServiceClient {
	return &filterModelServiceClient{cc}
}

func (c *filterModelServiceClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferResponse)
	err := c.cc.Invoke(ctx, FilterModelService_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterModelServiceServer implements classify-model Infer.
type FilterModelServiceServer interface {
	Infer(context.Context, *InferRequest) (*InferResponse, error)
	mustEmbedUnimplementedFilterModelServiceServer()
}

// UnimplementedFilterModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilterModelServiceServer struct{}

func (UnimplementedFilterModelServiceServer) Infer(context.Context, *InferRequest) (*InferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedFilterModelServiceServer) mustEmbedUnimplementedFilterModelServiceServer() {}
func (UnimplementedFilterModelServiceServer) testEmbeddedByValue()                            {}

// UnsafeFilterModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilterModelServiceServer will
// result in compilation errors.
type UnsafeFilterModelServiceServer interface {
	mustEmbedUnimplementedFilterModelServiceServer()
}

func RegisterFilterModelServiceServer(s grpc.ServiceRegistrar, srv FilterModelServiceServer) {
	// If the following call pancis, it indicates UnimplementedFilterModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilterModelService_ServiceDesc, srv)
}

func _FilterModelService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterModelServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterModelService_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterModelServiceServer).Infer(ctx, req.(*InferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilterModelService_ServiceDesc is the grpc.ServiceDesc for FilterModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilterModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easymail.filtermodel.v1.FilterModelService",
	HandlerType: (*FilterModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infer",
			Handler:    _FilterModelService_Infer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filtermodel/v1/filtermodel.proto",
}
